name: Run Tests
on:
  push:
    branches:
      - main
  release:
    types: [published]
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test with Python ${{matrix.python}} on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - macos
        - windows
        - ubuntu
        python:
        - 3.7
        - 3.8
        - 3.9

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Prepare Windows environment
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install wget --no-progress

    - name: Prepare Conda environment spec
      id: conda-lock
      shell: bash
      run: |
        bash lkbuild/lock-for-ci.sh -v $PYVER -b mkl
      env:
        RUNNER: ${{runner.os}}
        PYVER: ${{matrix.python}}

    - name: Initialize Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: csr
        environment-file: ${{steps.conda-lock.outputs.environment-file}}

    - name: 🔎 Inspect environment
      run: |
        numba -s

    - name: 🛠 Compile MKL helper
      run: |
        python build_mkl.py

    - name: Run tests
      run: |
        python -m pytest --cov=csr -v

    - name: Run tests without JIT
      run: |
        python -m pytest --cov=csr --cov-append --log-file=test-nojit.log --hypothesis-profile=nojit
      env:
        NUMBA_DISABLE_JIT: 1

    - name: Aggregate coverage data
      run: coverage xml

    - name: Upload coverage
      uses: codecov/codecov-action@v1

  sdist:
    name: Build Source Packages
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch Git tags
      run: git fetch --tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python deps
      run: pip install -U flit

    - name: Build distribution
      run: flit build

    - name: Save archive
      uses: actions/upload-artifact@v1
      with:
        name: pypi-pkgs
        path: dist

    - name: List dist dir
      run: ls -R dist

    - name: Publish PyPI packages
      if: github.event_name == 'release'
      run: |
        flit publish
      shell: bash
      env:
        TWINE_NON_INTERACTIVE: y
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}

