name: Run Tests
on: [push, pull_request]

jobs:
  test:
    name: Test with Python ${{matrix.python}} on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}-latest
    strategy:
      matrix:
        platform:
        - macos
        - windows
        - ubuntu
        python:
        - 3.6
        - 3.7
        - 3.8
        - 3.9
        exclude:
          - platform: macos
            python: 3.9

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python }}
        conda-channels: conda-forge

    - name: Locate Python
      run: |
        which python

  # sdist:
  #   name: Build Source Packages
  #   runs-on: ubuntu-latest
  #   needs: [test, lint, no-extras]

  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0

  #   - name: Fetch Git tags
  #     run: git fetch --tags

  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8

  #   - name: Install Python deps
  #     run: pip install -U flit

  #   - name: Build distribution
  #     run: flit build

  #   - name: Save archive
  #     uses: actions/upload-artifact@v1
  #     with:
  #       name: pypi-pkgs
  #       path: dist

  #   - name: List dist dir
  #     run: ls -R dist

  #   - name: Publish PyPI packages
  #     if: github.event_name == 'release'
  #     run: |
  #       flit publish
  #     shell: bash
  #     env:
  #       TWINE_NON_INTERACTIVE: y
  #       FLIT_USERNAME: __token__
  #       FLIT_PASSWORD: ${{ secrets.TWINE_TOKEN }}
