name: Run Tests
on:
  push:
    branches:
      - main
  release:
    types: [published]
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-conda:
    name: Test with Conda Python ${{matrix.python}} on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - macos
        - windows
        - ubuntu
        python:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Prepare Windows environment
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install wget --no-progress

    - name: Prepare Conda environment spec
      id: conda-lock
      shell: bash
      run: |
        bash lkbuild/lock-for-ci.sh -v $PYVER -m mkl-devel.yml
      env:
        RUNNER: ${{runner.os}}
        PYVER: ${{matrix.python}}

    - name: Initialize Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: csr
        environment-file: ${{steps.conda-lock.outputs.environment-file}}

    - name: 🔎 Inspect environment
      run: |
        numba -s

    - name: 🛠 Compile MKL helper
      run: |
        invoke build-mkl

    - name: Run tests
      run: |
        python -m pytest --cov=csr -v

    - name: Run tests without JIT
      run: |
        python -m pytest --cov=csr --cov-append --log-file=test-nojit.log --hypothesis-profile=nojit
      env:
        NUMBA_DISABLE_JIT: 1

    - name: Aggregate coverage data
      run: coverage xml

    - name: Upload coverage
      uses: codecov/codecov-action@v1

  test-vanilla:
    name: Test w/ Vanilla Python ${{matrix.python}} on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        platform:
        - windows
        - ubuntu
    steps:
      - name: Check out source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python}}
          architecture: x64

      - name: Set up Python build deps
        env:
          PIP_PREFER_BINARY: 'true'
        run: |
          python -m pip install -U flit wheel

      - name: Install CSR and its deps
        env:
          PIP_PREFER_BINARY: 'true'
        run: |
          flit install --pth-file --deps develop

      - name: Run tests
        run: |
          python -m pytest --cov=csr --cov-report=xml --log-file=test.log

      - name: Aggreagate Coverage Data
        run: coverage xml

      - name: Upload coverage
        uses: codecov/codecov-action@v1

  sdist:
    name: Build Source Packages
    runs-on: ubuntu-latest
    needs: [test-conda, test-vanilla]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch Git tags
      run: git fetch --tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python deps
      run: pip install -U flit

    - name: Build distribution
      run: flit build

    - name: Save archive
      uses: actions/upload-artifact@v1
      with:
        name: pypi-pkgs
        path: dist

    - name: List dist dir
      run: ls -R dist

    - name: Publish PyPI packages
      if: github.event_name == 'release'
      run: |
        flit publish
      shell: bash
      env:
        TWINE_NON_INTERACTIVE: y
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}

